language: r
dist: trusty
cache: packages
sudo: false

r: 3.6.1
warnings_are_errors: false
r_check_args: "--no-build-vignettes --no-manual --as-cran --no-examples"

r_packages:
  - covr
  - devtools
  - testthat

bioc_packages:
  - GenomicRanges

r_github_packages:
  - mskilab/gUtils

before_install:
    - curl -OL https://raw.githubusercontent.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    ##http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
    - chmod 755 ./travis-tool.sh

script:
- travis_wait 30 ./travis-tool.sh run_tests


after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - travis_wait Rscript -e 'covr::codecov()'


notifications:
  email:
      on_success: change
      on_failure: change
